#!/bin/sh 
readonly PROGNAME=$(basename $0)
readonly PROGDIR=$(readlink -m $(dirname $0))

usage(){
    cat <<EOF
usage: $PROGNAME [verbs] [all,list of modules to check out]

Checks out a local copy of each module's source code using git.  Use
the alias 'all' to check out all available modules in the hep-trunk
organization.

EXAMPLES:
    $PROGNAME get colors cut root-sugar tree-utils
    $PROGNAME get all
    $PROGNAME list
    $PROGNAME build all
    $PROGNAME install all
VERBS: 
    get               Git clone the target's git repo, update if exists
    rebuild           Re-compile target (runs 'make clean' first)
    build             Compile target
    install           Install target 
    uninstall         Uninstall target
    list              List all available modules
    help, -h, --help  Show this help
EOF
}
list(){
# When you add a new module to the organization, please include it
# here with a one line function describing what the module's purpose
# is.
    cat <<EOF
Use 'all' as an alias for every module in the list.

Module Name   Description
-----------   -----------
colors        Utilities for choosing unbiased colors
cut           A templated cut class and config file parser
root-sugar    Collection of functions to cleanly copy and retrieve root objects
tree-utils    Functions to help with setting up input and output variables for trees
EOF
}
# Add new modules to this list so that 'all' knows about it
all_modules(){
    local cmd=$1;
    proc_list $cmd "colors" "cut" "root-sugar" "tree-utils"
}

proc_list(){
    local cmd=$1;
    shift 1;
    local item;
    for item in $@; do
	$cmd $item
    done
}
git_clone(){
    local module=$1
    git clone git@github.com:hep-trunk/"$module".git "$module";
}
check_all(){
    local verb=$1
    shift 1
    if [ "$@" = "all" ]; then
	all_modules $verb
    else
	proc_list $verb $@
    fi
}
rebuild_module(){
    local module=$1
    local oldpwd=$PWD
    echo "Building: "$module
    cd $module;
    make clean; make;
    cd $oldpwd;
}
build_module(){
    local module=$1
    local oldpwd=$PWD
    echo "Building: "$module
    cd $module;
    make;
    cd $oldpwd;
}
get_module(){
    local module=$1
    local oldpwd=$PWD
    echo "Getting: "$module
    if [ -d $PWD/$module/.git ]; then
	cd $module;
	git pull;
	cd $oldpwd;
    else
	git_clone $module;
    fi
}
install_module(){
    local module=$1
    local oldpwd=$PWD
    echo "Installing: "$module
    cd $module;
    make install;
    cd $oldpwd;
}
uninstall_module(){
    local module=$1
    local oldpwd=$PWD
    echo "Uninstalling: "$module
    cd $module;
    make uninstall;
    cd $oldpwd;
    local module=$1
}
main(){
    local verb=$1
    shift 1
    local first_module=$1
    case "$verb" in
	build)
	    check_all build_module $@
	    ;;
	rebuild)
	    check_all rebuild_module $@
	    ;;
	list)
	    list;;
	get)
	    check_all get_module $@
	    ;;
	install)
	    check_all install_module $@
	    ;;
	uninstall)
	    check_all uninstall_module $@
	    ;;
	help)
	    usage;;
	-h)
	    usage;;
	--help)
	    usage;;
	*)
	    usage;;
    esac
  # usage;
}
main "$@"
